//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alarm
    {
        public long Id { get; set; }
        public Nullable<int> AlarmTypeId { get; set; }
        public string AlarmTypeTitle { get; set; }
        public Nullable<System.DateTime> GenerateDate { get; set; }
        public string GenerateUser { get; set; }
        public Nullable<int> GenerateTreatmentPhaseId { get; set; }
        public string GenerateTreatmentPhaseTitle { get; set; }
        public Nullable<bool> IsOnBoard { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public string ReviewUserName { get; set; }
        public string ReviewText { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
