//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlarmConfig
    {
        public int Id { get; set; }
        public Nullable<int> AlarmEventTypeId { get; set; }
        public Nullable<bool> SendDoctorSMS { get; set; }
        public Nullable<bool> SendPhysictSMS { get; set; }
        public Nullable<bool> SendResidentSMS { get; set; }
        public Nullable<bool> SendAdminSMS { get; set; }
        public Nullable<bool> SendAggregateSMS { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedUser { get; set; }
    
        public virtual AlarmEventType AlarmEventType { get; set; }
    }
}
