//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alarm
    {
        public long Id { get; set; }
        public Nullable<int> AlarmEventTypeId { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> PhysicUserId { get; set; }
        public Nullable<bool> IsSystemAlarm { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.DateTime> DeliverDate { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<bool> IsSMS { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> ResidentId { get; set; }
        public Nullable<int> TreatmentProcessId { get; set; }
        public string TreatmentProcessTitle { get; set; }
        public string PatientFullName { get; set; }
        public Nullable<long> MedicalRecordId { get; set; }
    }
}
