//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calendar
    {
        public long Id { get; set; }
        public Nullable<long> MedicalRecordId { get; set; }
        public string PatientFullName { get; set; }
        public string DoctorFullName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string PersianDate { get; set; }
        public Nullable<int> SessionNumber { get; set; }
        public Nullable<int> AttendanceStatusId { get; set; }
        public Nullable<int> PhysicTreatmentId { get; set; }
        public string TreatmentPhaseText { get; set; }
    
        public virtual MedicalRecord MedicalRecord { get; set; }
    }
}
