//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contour
    {
        public long Id { get; set; }
        public Nullable<long> MedicalRecordId { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string Description { get; set; }
        public string ExtraInfo1 { get; set; }
        public string ExtraInfo2 { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public string AcceptUser { get; set; }
    
        public virtual MedicalRecord MedicalRecord { get; set; }
    }
}
