//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContourDetails
    {
        public long Id { get; set; }
        public Nullable<long> MediacalRecordId { get; set; }
        public Nullable<long> ContourId { get; set; }
        public Nullable<int> CancerOARId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> SelectDate { get; set; }
    
        public virtual Contour Contour { get; set; }
    }
}
