//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicTreatmentPlanHostory
    {
        public int Id { get; set; }
        public Nullable<int> PhysicTreatmentPlanId { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string ActionUser { get; set; }
        public Nullable<bool> HasAlarm { get; set; }
        public Nullable<bool> IsDoctor { get; set; }
    
        public virtual PhysicTreatmentPlan PhysicTreatmentPlan { get; set; }
    }
}
