//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicUserAlarm
    {
        public int Id { get; set; }
        public Nullable<int> PhysicUserId { get; set; }
        public Nullable<bool> IsSmsRecieveActive { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
    
        public virtual PhysicUser PhysicUser { get; set; }
    }
}
