//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicTreatment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhysicTreatment()
        {
            this.PhysicTreatmentPlan = new HashSet<PhysicTreatmentPlan>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MedicalRecordId { get; set; }
        public Nullable<int> PhaseNumber { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string ActionUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicTreatmentPlan> PhysicTreatmentPlan { get; set; }
    }
}
