//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicTreatmentPlanDetail
    {
        public long Id { get; set; }
        public int PhysicTreatmentPlanId { get; set; }
        public Nullable<long> MedicalRecordId { get; set; }
        public string PatientFirstName { get; set; }
        public string PatientLastName { get; set; }
        public Nullable<int> CancerOARId { get; set; }
        public string CancerOARIdValue { get; set; }
        public string CancerOARTitle { get; set; }
        public string CancerOARTolerance { get; set; }
        public Nullable<int> CancerTargetId { get; set; }
        public string CancerTargetTitle { get; set; }
        public string CancerTargetValue { get; set; }
        public string CancerTargetOptimum { get; set; }
        public Nullable<int> PlanNo { get; set; }
    }
}
