//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicTreatmentPlan
    {
        public int Id { get; set; }
        public int PlanNo { get; set; }
        public long MedicalRecordId { get; set; }
        public int PhysicId { get; set; }
        public string PhysicFullName { get; set; }
        public Nullable<System.DateTime> PhysicApplyDate { get; set; }
        public string PhysicComment { get; set; }
        public Nullable<bool> IsApprovedByDoctor { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public string DoctorFullName { get; set; }
        public string DoctorComment { get; set; }
        public Nullable<int> Fields { get; set; }
        public Nullable<int> TreatmentPhaseId { get; set; }
        public Nullable<int> TreatmentPhaseNo { get; set; }
    }
}
