//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentPhase
    {
        public long Id { get; set; }
        public Nullable<long> MedicalRecordId { get; set; }
        public string PatientFirstName { get; set; }
        public string PatientLastName { get; set; }
        public Nullable<int> TreatmentDeviceId { get; set; }
        public string TreatmentDeviceTitle { get; set; }
        public Nullable<int> PhaseNumber { get; set; }
        public string PhaseText { get; set; }
        public Nullable<int> Fraction { get; set; }
        public string Target { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PrescribeDate { get; set; }
        public string PrescribesdUserId { get; set; }
        public string PrescribesdUserFullName { get; set; }
        public string PrescribedUserRole { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsPrescribedByDoctor { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string ApprovedUserFullName { get; set; }
        public Nullable<bool> Reserve1 { get; set; }
        public Nullable<bool> Reserve2 { get; set; }
        public string Reserve3 { get; set; }
    }
}
