//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentPhase
    {
        public long Id { get; set; }
        public Nullable<long> MedicalRecordId { get; set; }
        public Nullable<int> PhaseNumber { get; set; }
        public string PhaseText { get; set; }
        public Nullable<double> Dose { get; set; }
        public Nullable<int> Fraction { get; set; }
        public string Target { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PrescribeDate { get; set; }
        public string PrescribesdUser { get; set; }
        public Nullable<int> TreatmentDeviceId { get; set; }
    }
}
