//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysicManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TreatmentCategoryService
    {
        public int Id { get; set; }
        public Nullable<int> TreatmentCategoryId { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int RelativeValue { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TreatmentCategory TreatmentCategory { get; set; }
    }
}
